[build]
  base = "budgetpilot-frontend"
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  

# SPA 새로고침 404 방지
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 프론트에서 /api/* 요청 → 서버리스 함수로 라우팅
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
